### ISSUE TITLE
Staging env variables are not loaded

### ISSUE THREAD

**Issue by clabnet** [iendeavor/import-meta-env#95]
Hello,

my environment is Windows 10, Node: 16.14.0 - npm: 8.5.1 - pnpm: 7.14.1 - Vue 3.2 - Vite 3.2

**package.json**
```
"scripts": {
    "dev": "vite",
    "staging": "vite build  --mode staging",
    "build": "vite build",
    "serve": "import-meta-env -x .env && vite preview"
  },
```
I have five **.env files** : 
```
# .env
ENVIRONMENT = ENV
HOST = http://host-env.westeurope.cloudapp.azure.com

# .env.example
ENVIRONMENT = EXAMPLE
HOST = http://host-example.westeurope.cloudapp.azure.com

# .env.development
VITE_ENVIRONMENT = DEV
VITE_HOST = http://host-dev.westeurope.cloudapp.azure.com

# .env.production
VITE_ENVIRONMENT = PRODUCTION
VITE_HOST = http://host-production.westeurope.cloudapp.azure.com

# .env.staging
NODE_ENV=production
VITE_ENVIRONMENT = STAGING
VITE_HOST = http://host-staging.westeurope.cloudapp.azure.com
```

On .env.xxxx the keys are prefixed by VITE_ and these values are **write correctly** into each environment.

The values ENVIRONMENT and HOST are write correctly into **production build**, and are **NOT** correctly into **staging build**.
 
My workflow is : 

Once time: 
`npx import-meta-env-typescript -x .env.example`

Then:

`pnpm dev`  >> all running fine, 
 - import.meta.env.ENVIRONMENT is ENV 
 - import.meta.env.VITE_ENVIRONMENT is DEV
 
`pnpm build` >> `pnpm serve` >> all running fine
 - import.meta.env.ENVIRONMENT is ENV 
 - import.meta.env.VITE_ENVIRONMENT is PRODUCTION
 
Now change the .env file setting ENVIRONMENT = PROD and restart `pnpm serve` >> all running fine
 - import.meta.env.ENVIRONMENT is PROD 
 - import.meta.env.VITE_ENVIRONMENT is PRODUCTION
 
Building now on staging mode :
`pnpm staging`

Now change the .env file setting ENVIRONMENT = STAGING   and    CTRL+SHIFT+P to Reload Window on VSCODE

`pnpm serve` >> 
 - import.meta.env.ENVIRONMENT is PROD     **!!!!!!! This is the error, for me.  I would expect = STAGING**
 - import.meta.env.VITE_ENVIRONMENT is STAGING  ** OK, is correct

I missing a thing ?

Thank's

**Comment by iendeavor** [comment]
@clabnet

The problem is due to `--mode staging`, which makes `@import-meta-env/unplugin` _inline_ your environment variables instead of putting placeholders. (i.e., after running `npm staging`, we no longer have the opportunity to inject environment variables.)

If you want to build the production (inject environment variables after the build stage) in modes other than production, you need to explicitly set [`shouldInlineEnv` option](https://iendeavor.github.io/import-meta-env/api.html#import-meta-env-unplugin) to `true`.

In your scenario, you can fix it by:

```ts
// vite.config.ts
import ImportMetaEnvPlugin from "@import-meta-env/unplugin";

export default {
  plugins: [
    ImportMetaEnvPlugin.vite({
      example: ".env.example",
      shouldInlineEnv: process.env.IMPORT_META_ENV_MODE === 'production',
  ],
};
```

```sh
$ export IMPORT_META_ENV_MODE=production
$ pnpm run build --mode staging
```

---

The scripts you use need be fixed too: `-x` is abbreviation for `--example`:
- ❌ : `"serve": "import-meta-env -x .env && vite preview"`
- ✅ : `"serve": "import-meta-env -e .env -x .env.example && vite preview"` (`-e .env` is optional, since default value of `-e` is `.env`)

BTW, we don't encourage using both compile-time and runtime environment variables in the same project, which can make it difficult for us to debug our code. Also, using a `.env` file as the source of truth could make things simpler.

**Comment by clabnet** [comment]
Very much satisfied from your response.
It work fine after update the `serve` command and `vite.config.ts`. 
I could close the issue. Thank's.
